### ISSUE TITLE
CollectionControl.AddNew could overwirte initialized in constructor properties.

### ISSUE THREAD

**Issue by mitkodi** [xceedsoftware/wpftoolkit#1159]
**CollectionControl.AddNew** tries to set *newItem's* generic properties which could overwrite existing values (already set in the *newItem's* constructor). In addition it could raise exception if those properties don't have default constructors.
It would be better to not set properties which current values are not null.

(*we can overcome this by declaring generic properties as read-only but it will break cloning items in CollectionControlDialog*)

**Comment by XceedBoucherS** [comment]
Hi,

This is probably already fixed in latest versions.
Could you send a sample showing the problem so I could validate ?
Thanks.

**Comment by mitkodi** [comment]
In the last version of **CollectionControl.AddNew** I can see the following:
```
if( property.CanWrite && property.PropertyType.IsGenericType )
{
  var genericCollection = Activator.CreateInstance( property.PropertyType );
  property.SetValue( newItem, genericCollection, null );
}
```
Which will nullify generic properties that could be initialized in the constructor. So I think the bug is still there.

Btw, I think that the name *genericCollection* is not the best one because there could be generic properties that are not collections or may be you should add condition for implementing of *ICollection*?

**Comment by XceedBoucherS** [comment]
Hi,

Yes, I can confirm that this code has been removed in latest versions :
-v3.4 and up don't have this code.
-If you have the community edition, you should have v3.1.
Community edition edition is always some versions behind.
On the other hand I can't confirm this will fix your case. Please send a sample or wait for v3.4, or buy the latest version : v3.5 will be released shortly.

**Comment by mitkodi** [comment]
OK, Thank you. I'll wait for the 3.4 community edition...
