### ISSUE TITLE
Serializing AvalonDock result in a malformed xml

### ISSUE THREAD

**Issue by Alcruz** [xceedsoftware/wpftoolkit#1227]
I am serializing the DockManager and then adding a layout version. `The SaveLayoutVersion() ` is using .NET XML API and is throwing a exception.
```
			try
			{
				var serializer = new XmlLayoutSerializer(this.controller.MainView.DockManager);
				using (var stream = new StreamWriter(dockingConfigFile))
					serializer.Serialize(stream);
				SaveLayoutVersion();
			}
			catch (Exception exception)
			{
				throw new Exception($"The following error occurred when trying to save the window layout of Linx designer. {exception.Message}");
			}
```

XML (Look for the hidden element, at the bottom)
```
<?xml version="1.0" encoding="utf-8"?>
<LayoutRoot>
  <RootPanel Orientation="Horizontal">
    <LayoutAnchorablePaneGroup Orientation="Vertical" DockWidth="325">
      <LayoutAnchorablePane DockWidth="325">
        <LayoutAnchorable AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Solution Explorer" IsSelected="True" ContentId="SolutionControlDockContent" />
      </LayoutAnchorablePane>
      <LayoutAnchorablePane>
        <LayoutAnchorable AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Properties" IsSelected="True" ContentId="PropertyControlDockContent" />
        <LayoutAnchorable AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Output" ContentId="OutputControlDockContent" />
      </LayoutAnchorablePane>
    </LayoutAnchorablePaneGroup>
    <LayoutPanel Orientation="Vertical" DockHeight="250">
      <LayoutDocumentPane />
      <LayoutAnchorablePaneGroup Orientation="Horizontal" DockHeight="200">
        <LayoutAnchorablePane Id="ac0e2183-f47a-4e62-a210-e876fa0ca9be" DockHeight="200">
          <LayoutAnchorable AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Validations" IsSelected="True" ContentId="ValidationControlDockContent" />
        </LayoutAnchorablePane>
        <LayoutAnchorablePane>
          <LayoutAnchorable CanHide="False" AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Debug Output" IsSelected="True" ContentId="DebugOutputControlDockContent" CanClose="False" />
        </LayoutAnchorablePane>
        <LayoutAnchorablePane>
          <LayoutAnchorable CanHide="False" AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Debug Values" IsSelected="True" ContentId="DebugValueControlDockContent" CanClose="False" />
        </LayoutAnchorablePane>
      </LayoutAnchorablePaneGroup>
    </LayoutPanel>
    <LayoutAnchorablePaneGroup Orientation="Vertical" DockWidth="325">
      <LayoutAnchorablePane DockWidth="325" DockHeight="3*">
        <LayoutAnchorable AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Plugins" IsSelected="True" ContentId="PluginControlDockContent" />
      </LayoutAnchorablePane>
    </LayoutAnchorablePaneGroup>
  </RootPanel>
  <TopSide />
  <RightSide />
  <LeftSide />
  <BottomSide />
  <FloatingWindows />
  <Hidden AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Search Results" ContentId="SearchControlDockContent" PreviousContainerId="ac0e2183-f47a-4e62-a210-e876fa0ca9be" PreviousContainerIndex="0" AutoHideMinWidth="100" AutoHideMinHeight="100" Title="References To" ContentId="FindReferencesControlDockContent" PreviousContainerId="ac0e2183-f47a-4e62-a210-e876fa0ca9be" PreviousContainerIndex="0" />
</LayoutRoot>
```

**Comment by XceedBoucherS** [comment]
Hi, I don't have your XAML to reproduce the issue, but I'm pretty sure I've seen this bug and it's already fixed in latest versions.
Current version is :
v3.5 : Plus edition
v3.2 : Open Source edition
The Plus edition is always 2-3 releases after the OpenSource version. 
Next versions will be :
v3.6 : Plus edition
v3.3 : Open Source edition
You can get the Plus version here : https://xceed.com/xceed-toolkit-plus-for-wpf/
Thanks.

**Comment by RyanYANG52** [comment]
Bug1: LayoutRoot.cs  WirteXml(XmlWriter writer)
```
          foreach( var layoutAnchorable in Hidden )
          {
//writer.WriteStartElement(layoutAnchorable .GetType().Name);
            layoutAnchorable.WriteXml( writer );
//writer.WriteEndElement();
          }
```
Bug2: LayoutRoot.cs List<object> ReadElementList( XmlReader reader )
**Missing**
```
			while (reader.NodeType == XmlNodeType.Whitespace)
			{
				reader.Read();
			}
```
Bug3: Orientation for RootPanel [https://github.com/xceedsoftware/wpftoolkit/issues/1202](url)

@Alcruz you can wirte you own Serialize and Deserialize method, or use 3.1 instead (which didnot use IXmlSerializable) I'm speechless about those bugs

**Comment by Alcruz** [comment]
@XceedBoucherS, I am using the latest version of the opensource library and still have the same problem. @RyanYANG52 Thanks, I'll try that.

**Comment by XceedBoucherS** [comment]
@Alcruz , Have you tried with Toolkit v3.5 Plus edition? If you are still experiencing the problem in that version, please attach your XAML and the code to Serialize/De-serialize so I can reproduce the bug.

Here are the changes for AvalonDock in the latest releases :
v3.3 : 
-In AvalonDock, an AutoHide LayoutAnchorable will now always appear on top of other controls.
-In AvalonDock, LayoutAnchorables can now be closed when their CanClose property is set to true. Or, they can now be hidden when their CanHide property is true.
-In AvalonDock, pinning a LayoutAnchorable to a LayoutAnchorSide will no longer crash after loading a Layout.
-In AvalonDock, Deserializing a layout with AutoHidden LayoutAnchorables will no longer crash.
-In AvalonDock, un-hiding a LayoutAnchorable after deserialization will no longer make the Layoutanchorable disappear. 
-In AvalonDock, using a style selector (property DockingManager.LayoutItemContainerStyleSelector) with the DockingManager.DocumentsSource property will now apply the desired style.
-In AvalonDock, resizing a LayoutAnchorable after a theme change will no longer cause a crash.
-In AvalonDock, using a FloatingWindow will no longer display only parts of the content.

v3.4 : 
-In AvalonDock, theming for Windows10 will now be possible through MergedDictionaries.
-In AvalonDock, LayoutDocuments now have the possibility to be ‘pinned’ in a LayoutDocumentPane.
-In AvalonDock, Deserialization using a StringReader no longer throws an exception.
-In AvalonDock, when no LayoutDocumentPane is defined, auto-hiding a LayoutAnchorable no longer automatically docks it to the right.
-In AvalonDock, the NavigatorWindow now accepts the Tab key to select LayoutAnchorable or LayoutDocument items.
-In AvalonDock, using Ctrl + Tab to select a new LayoutAnchorable/LayoutDocument now properly sets the focus on the selected item.
-In AvalonDock, docking a LayoutAnchorable in a LayoutDocumentPane now shows its close button.
-In AvalonDock, the orientation of the RootPanel is now correctly set after de-serialization.
-In AvalonDock, deserializing no longer makes the LayoutDocuments icons disappear.
-In AvalonDock, serializing with hidden LayoutAnchorables no longer causes a crash.
-In AvalonDock, LayoutAnchorables no longer remain hidden after calling LayoutAnchorable.Show().
-In AvalonDock, LayoutDocumentPanes are now hidden when all its children become invisible.

v3.5:
-In AvalonDock, dropping a LayoutDocument or LayoutAnchorable from a DockingManager to a nested DockingManager will no longer be allowed.
-In AvalonDock, changing the theme while a Layout floating window is active will no longer cause a crash.
-In AvalonDock, setting a Background on an implicit style for a LayoutAnchorSideControl will now work.
-In AvalonDock, side panels will now be extended to the DockingManager’s control limits.
-In AvalonDock, the Alt key adornments will now work when items are defined in a DataTemplate of a resource dictionary.
-In AvalonDock, the new CreateFloatingWindow method will now be available to create a new LayoutAnchorableFloatingWindow or LayoutDocumentFloatingWindow with a content that can be immutable.
-In AvalonDock, modifying the content of a floating window will now resize the window according to its SizeToContent property.
-In AvalonDock, auto-hiding a LayoutAnchorable will no longer anchor it on the opposite side.
-In AvalonDock, re-ordering LayoutAnchorable TabItems will no longer cause a crash.
-In AvalonDock, the new LayoutAnchorable.CanDockAsTabbedDocument property is now available to prevent docking a LayoutAnchorable in a LayoutDocumentPane.
-In AvalonDock, the new LayoutDocument.CanMove property is now available to prevent moving a LayoutDocument.
-In AvalonDock, auto-hidden LayoutAnchorables will now be draggable to a floating window.
-In AvalonDock Metro Theme, un-selecting a LayoutAnchorable will no longer create a jump of 3 pixels.
-In AvalonDock, opening an auto-hide window while the “Visual Studio UI Debugging Tools for XAML” is enabled will no longer cause a crash.

Thanks.

**Comment by li0nsar3c00l** [comment]
Any ETA, when the fix to this bug will get pushed to the free branch?

**Comment by XceedBoucherS** [comment]
Hi,
The fix will be pushed in the free branch when a free version is released.
Currently, 
-The users of the Plus version have: v3.6 (you can try it here : https://xceed.com/xceed-toolkit-plus-for-wpf/). The PLus version is always some versions ahead and contains more features.
-The users of the Free version have : v3.3.
The next release could be end of spring, beginning of summer.
Thank you.
