### ISSUE TITLE
Detaching the tab makes the content of the tab disapear

### ISSUE THREAD

**Issue by vbaros** [xceedsoftware/wpftoolkit#1561]
I'm using version 3.6.0.
If I come back to version 3.4.0 the issue is gone.

Dragging the document which is attached as a tab to be a freeform window makes all the content of the detached tab disappear.
The problem is that I also can't go back to version 3.4.0 which doesn't exist on Nuget any more.

**Comment by XceedBoucherS** [comment]
Hi,

Have you tried with v3.7, or the latest v3.8 version ?
I'm pretty sure this issue is already fixed.

**Comment by vbaros** [comment]
I tried it on version 3.7 and now I just tried it on version 3.8 which was just released a few hours ago. Still the same problem unfortunately.

**Comment by XceedBoucherS** [comment]
Hi,
Can you submit your sample code so we can analyse it ?
You only drag a LayoutDocument (wit content) so it becomes a LayoutDocumentFloatingWindow and this floatingWindow do not have content anymore ?
What version of Windows are you using ?
Thank you.

**Comment by Linchy** [comment]
I also have this issue, Xaml:

```
<UserControl x:Class="Views.TestView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:Views"
             xmlns:xcad="http://schemas.xceed.com/wpf/xaml/avalondock"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid Grid.Column="1" Margin="4,0,0,0">
        <Grid.RowDefinitions>
            <RowDefinition Height="30"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Menu>       
        </Menu>
        <xcad:DockingManager Name="dockManager" Grid.Row="1"
                           AllowMixedOrientation="False"
                           BorderBrush="Black"
                           BorderThickness="1">
            <xcad:DockingManager.DocumentHeaderTemplate>
                <DataTemplate>
                    <StackPanel Orientation="Horizontal">
                        <Grid Background="{Binding Foreground}" Margin="0,-2,4,0" Width="8" Height="8"/>
                        <TextBlock Text="{Binding Title}" />
                    </StackPanel>
                </DataTemplate>
            </xcad:DockingManager.DocumentHeaderTemplate>
            <xcad:LayoutRoot x:Name="_layoutRoot">
                <xcad:LayoutPanel Orientation="Horizontal">
                    <xcad:LayoutDocumentPane>
                        <xcad:LayoutDocument Title="Configuration Editor">
                            <Button Content="Test" />
                        </xcad:LayoutDocument>                  
                    </xcad:LayoutDocumentPane>

                </xcad:LayoutPanel>
            </xcad:LayoutRoot>
        </xcad:DockingManager>
    </Grid>
</UserControl>
```

Packages.config:
```
<packages>
  <package id="AvalonEdit" version="6.0.1" targetFramework="net471" />
  <package id="Extended.Wpf.Toolkit" version="3.8.1" targetFramework="net471" />
  <package id="WPFThemes.DarkBlend" version="1.0.8" targetFramework="net471" />
  <package id="Xceed.Wpf.AvalonDock.Themes.VS2013" version="2.9.0.1" targetFramework="net471" />
</packages>
```

**Comment by XceedBoucherS** [comment]
Hi,

I've created a sample project and filled the Window content (in XAML) with the XAML you copied here. Under v3.8.1, downloaded from Nuget, I can drag the LayoutDocument so it becomes a LayoutDocumentFloatingWindow. The content(a button) is still visible in the floatingWindow.
Maybe this has something to do with the theming or any other configuration.
Please try your sample code in a new project.
Thank you.

**Comment by Linchy** [comment]
Ah yes I tried it and it worked, it seems to be a problem with "Xceed.Wpf.AvalonDock.Themes.VS2013".

Removing this line fixes the floating issue at least:
```
this.dockManager.Theme = new Vs2013DarkTheme();
```

I didn't realise a theme could do that, if I go back to "Extended.Wpf.Toolkit" version="3.4.0", then the dragging of tabs work. I wonder if the xaml changed somehow since then, breaking the theme?

**Comment by XceedBoucherS** [comment]
"Xceed.Wpf.AvalonDock.Themes.VS2013" is not a theme created by Xceed (the owner of the toolkit). Maybe the XAML has changed to fix other issues, but the XMAL didn't changed in the '"Xceed.Wpf.AvalonDock.Themes.VS2013" theme.
