### ISSUE TITLE
DropDownButton should mimic ComboBox behavior more closely

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#220]
<b>kentcb[CodePlex]</b> <br />Specifically, I had these things in mind:
nbsp

Pressing space when the DropDownButton is focussed should open the drop-down.
Pressing escape when the drop-down is open should close it. When the drop-down is open and the user clicks the button again, the drop-down should close and not immediately re-open.

**Comment by xceedsoftware** [comment]
Resolved with changeset 82913.

**Comment by xceedsoftware** [comment]
<b>brianlagunas[CodePlex]</b> <br />

A combobox does not open when pressing the space key. This works as described This works as described

**Comment by ZionGates** [comment]
> Resolved with changeset 82913.

Greetings, I'm using DotNetProjects.Wpf.Extended.Toolkit.dll in a DOT NET Core app.
This bug still lives, seems persistent. I've been looking for a solution, that's why I'm here.
Clicking the DropDownButton button should close the _existing_ Popup (if there is one)
 not close the popup and reopen it immediately.
Please how is this addressed?

**Comment by ZionGates** [comment]
Version 5 of the Dot.net core DotNetProjects.Wpf.Extended.Toolkit
![image](https://user-images.githubusercontent.com/1215869/157491002-3fb33311-6562-4095-8e76-6d1d84a70127.png)

**Comment by XceedBoucherS** [comment]
Hello,
This is not our product. 
We are Xceed Software, the owner of the Extended Wpf Toolkit project.

I can find DotNetProjects.Wpf.Extended.Toolkit on "https://www.nuget.org/packages/DotNetProjects.Extended.Wpf.Toolkit/"
From there, we can follow the "Project Web Site" link which links to jogibear9988's product, which he copied from Xceed. We don't know what he modified from our original Toolkit.

Please try the original version from "https://github.com/xceedsoftware/wpftoolkit" or the paid version from "https://xceed.com/en/our-products/product/toolkit-plus-for-wpf".
If you find any bugs or you have specific demands, just tell us :-)
Thank you.

**Comment by ZionGates** [comment]
Excellent, thanks for the update. I got the paid version and I'm delighted to see that bug is squashed.
